// <auto-generated />
using System;
using System.Collections.Generic;
using KnittingApp;
using KnittingApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnittingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601140943_KnittingAppMigrations")]
    partial class KnittingAppMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnittingApp.Form", b =>
                {
                    b.Property<Guid>("formId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Parts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("formId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("KnittingApp.Models.DraftModel", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EndPointY")
                        .HasColumnType("double precision");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("KnittingApp.Models.LoopMapModel", b =>
                {
                    b.Property<Guid>("LoopMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoopsReaderId")
                        .HasColumnType("uuid");

                    b.Property<Point>("NullPoint")
                        .HasColumnType("jsonb");

                    b.Property<double>("loopHeight")
                        .HasColumnType("double precision");

                    b.Property<string>("loopMapJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("loopWidth")
                        .HasColumnType("double precision");

                    b.Property<int>("nullM")
                        .HasColumnType("integer");

                    b.Property<int>("nullN")
                        .HasColumnType("integer");

                    b.HasKey("LoopMapId");

                    b.HasIndex("LoopsReaderId");

                    b.ToTable("LoopMaps");
                });

            modelBuilder.Entity("KnittingApp.Models.LoopsReaderModel", b =>
                {
                    b.Property<Guid>("LoopReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoopMapId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("SpentTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoopReaderId");

                    b.ToTable("LoopReaders");
                });

            modelBuilder.Entity("KnittingApp.Models.ModelModel", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackDraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackLoopMapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrontDraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrontLoopMapId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeasuresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SleeveDraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SleeveLoopMapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ModelId");

                    b.HasIndex("BackDraftId");

                    b.HasIndex("BackLoopMapId");

                    b.HasIndex("FrontDraftId");

                    b.HasIndex("FrontLoopMapId");

                    b.HasIndex("SleeveDraftId");

                    b.HasIndex("SleeveLoopMapId");

                    b.HasIndex("UserId");

                    b.HasIndex("ModelName", "UserId")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("KnittingApp.Models.SchemaModel", b =>
                {
                    b.Property<Guid>("SchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoopMapId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SchemaId");

                    b.HasIndex("LoopMapId");

                    b.HasIndex("SchemaName", "UserId")
                        .IsUnique();

                    b.ToTable("Schemas");
                });

            modelBuilder.Entity("KnittingApp.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KnittingApp.Models.LoopMapModel", b =>
                {
                    b.HasOne("KnittingApp.Models.LoopsReaderModel", "LoopsReader")
                        .WithMany()
                        .HasForeignKey("LoopsReaderId");

                    b.Navigation("LoopsReader");
                });

            modelBuilder.Entity("KnittingApp.Models.ModelModel", b =>
                {
                    b.HasOne("KnittingApp.Models.DraftModel", "BackDraft")
                        .WithMany()
                        .HasForeignKey("BackDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.LoopMapModel", "BackLoopMap")
                        .WithMany()
                        .HasForeignKey("BackLoopMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.DraftModel", "FrontDraft")
                        .WithMany()
                        .HasForeignKey("FrontDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.LoopMapModel", "FrontLoopMap")
                        .WithMany()
                        .HasForeignKey("FrontLoopMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.DraftModel", "SleeveDraft")
                        .WithMany()
                        .HasForeignKey("SleeveDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.LoopMapModel", "SleeveLoopMap")
                        .WithMany()
                        .HasForeignKey("SleeveLoopMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittingApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackDraft");

                    b.Navigation("BackLoopMap");

                    b.Navigation("FrontDraft");

                    b.Navigation("FrontLoopMap");

                    b.Navigation("SleeveDraft");

                    b.Navigation("SleeveLoopMap");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnittingApp.Models.SchemaModel", b =>
                {
                    b.HasOne("KnittingApp.Models.LoopMapModel", "LoopMap")
                        .WithMany()
                        .HasForeignKey("LoopMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopMap");
                });
#pragma warning restore 612, 618
        }
    }
}
